(function(){
const URL="https://fumxjavilkzysysnbjod.supabase.co",KEY="sb_publishable_ycwADAQzKsCW4BKot3c12w_8o4Ny6nC";
let db,session,ready=false,timer;
const $=id=>document.getElementById(id),show=id=>$(id).classList.remove("hidden"),hide=id=>$(id).classList.add("hidden");
function status(t,tone="neutral"){$("cloudSaveStatus").textContent=t;$("cloudSaveStatus").dataset.tone=tone}
function ui(){const e=session?.user?.email;$("accountBtn").textContent=e?"Account":"Sign in";$("accountEmail").textContent=e||"Not signed in";$("signedOutPanel").classList.toggle("hidden",!!e);$("signedInPanel").classList.toggle("hidden",!e);if(!e)status("Local save")}
async function put(data){if(!ready||!session)return;status("Saving...","working");const{error}=await db.from("player_saves").upsert({user_id:session.user.id,save_data:data,updated_at:new Date().toISOString()},{onConflict:"user_id"});status(error?"Cloud save failed":"Cloud saved",error?"error":"success")}
function queue(data){if(!ready||!session)return;clearTimeout(timer);timer=setTimeout(()=>put(structuredClone(data)),800)}
async function resolve(){ready=false;status("Checking cloud...","working");const{data,error}=await db.from("player_saves").select("save_data,updated_at").eq("user_id",session.user.id).maybeSingle();if(error){status("Cloud unavailable","error");return}const api=window.ParkEmpireSaveAPI;if(api.hasExistingLocalSave()){window.__pendingCloud=data;$("migrationCloudDetail").textContent=data?"A cloud park also exists. Choose which park to keep.":"No cloud park exists yet. Upload this park or start fresh.";$("useCloudBtn").textContent=data?"Use Cloud Park":"Start Fresh";show("migrationModal");status("Choice required","warning");return}ready=true;if(data?.save_data)api.applyCloudSave(data.save_data);else await put(api.getSaveData())}
async function auth(create){const email=$("authEmail").value.trim(),password=$("authPassword").value,msg=$("authMessage");if(!email||password.length<6){msg.textContent="Enter an email and password of at least 6 characters.";return}const r=create?await db.auth.signUp({email,password,options:{emailRedirectTo:location.href.split("#")[0]}}):await db.auth.signInWithPassword({email,password});msg.textContent=r.error?r.error.message:(r.data.session?"":"Check your email to confirm your account.");if(r.data.session)hide("accountModal")}
window.ParkEmpireCloud={scheduleUpload:queue};
document.addEventListener("DOMContentLoaded",async()=>{$("accountBtn").onclick=()=>show("accountModal");$("accountCloseBtn").onclick=()=>hide("accountModal");$("signInBtn").onclick=()=>auth(false);$("createAccountBtn").onclick=()=>auth(true);$("logoutBtn").onclick=async()=>{ready=false;await db.auth.signOut();hide("accountModal")};$("uploadLocalBtn").onclick=async()=>{hide("migrationModal");ready=true;await put(window.ParkEmpireSaveAPI.getSaveData())};$("useCloudBtn").onclick=async()=>{const c=window.__pendingCloud;hide("migrationModal");if(c?.save_data)window.ParkEmpireSaveAPI.applyCloudSave(c.save_data);else window.ParkEmpireSaveAPI.startFreshForCloud();ready=true;if(!c)await put(window.ParkEmpireSaveAPI.getSaveData());else status("Cloud loaded","success")};db=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});session=(await db.auth.getSession()).data.session;ui();if(session)await resolve();db.auth.onAuthStateChange((_e,s)=>{const changed=s?.user?.id!==session?.user?.id;session=s;ui();if(s&&changed)setTimeout(resolve,0);if(!s)ready=false})});
})();
